export const GET_INTERVENTIONS = 'GET_INTERVENTIONS';
export const GET_INTERVENTIONS_FULFILLED = `${GET_INTERVENTIONS}_FULFILLED`;
export const GET_INTERVENTIONS_ERROR = `${GET_INTERVENTIONS}_ERROR`;

export const CREATE_INTERVENTION = 'CREATE_INTERVENTION';
export const CREATE_INTERVENTION_FULFILLED = `${CREATE_INTERVENTION}_FULFILLED`;
export const CREATE_INTERVENTION_ERROR = `${CREATE_INTERVENTION}_ERROR`;
